version: 0.2

env:
  variables:
    GITHUB_REPO_URL: https://github.com/sudhakarbastawade2303/code-pipeline-project.git
    GITHUB_BRANCH: master
    KUBE_CONFIG: /root/.kube/config
    EKS_CLUSTER_NAME: your-cluster-name
    AWS_REGION: your-region

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
    - echo "Installing tools..."
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.4/2023-09-14/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/
    - pip install --upgrade awscli
    - yum install -y git

  pre_build:
    commands:
    - echo "Setting up kubeconfig"
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - echo "Cloning public repo: $GITHUB_REPO_URL"
    - git clone -b $GITHUB_BRANCH $GITHUB_REPO_URL
    - cd terraform-code

  build:
    commands:
    - echo "Deploying YAML file to Kubernetes"
    - kubectl apply -f terraform-code/complete-deploy.yml
    - echo "Waiting for front-end rollout..."
    - kubectl rollout status deployment/front-end -n sock-shop --timeout=180s

  post_build:
    commands:
    - echo "Deployment done. Listing services:"
    - kubectl get svc -n sock-shop
    - kubectl get pods -n sock-shop

artifacts:
  files: []
